export const lotofacil = 'lotofacil'
export const megaSena = 'mega-sena'
export const quina = 'quina'
export const duplaSena = 'dupla-sena'
export const lotomania = 'lotomania'
export const timenania = 'timemania'
export const diaDeSorte = 'dia-de-sorte'